### ISSUE TITLE
How to start a curve from a given point??

### ISSUE THREAD

**Issue by tasmiaorni** [rcannood/princurve#32]
Hello, I was using principal curve fitting  package : **principal_curve** in R . I am stuck in one point. How can I make my curve starting from a specific point that I put as an input in **start** parameter of the package.
Thanks

**Comment by rcannood** [comment]
Hello Tasmia,

The start parameter is used to define a starting curve, not a starting point. You could specify a curve that goes through your starting point and some other point in your dataset, but this is not guaranteed to return a curve which starts from your starting point.

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Hello Tasmia, 

I assume my reply solved your issue. Feel free to reopen this issue if this was not the case.

Kind regards,
Robrecht
